# Generated by Django 2.2 on 2020-05-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.URLField(max_length=255),
        ),
    ]
