# Generated by Django 2.2 on 2020-05-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
